In [1]:
import numpy as np
import pandas as pd

# Тема “Вычисления с помощью Numpy”

### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [12]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

_не совсем понял, почему должно быть 2 элемента, если мы считаем среднее значение по столбцам (признакам),
сделаю оба варианта_

In [35]:
# Среднее значение по каждому наблюдению
mean_a_row1 = a[0].mean()
mean_a_row2 = a[1].mean()
mean_a_row = np.array([mean_a_row1, mean_a_row2])
mean_a_row

array([2. , 8.4])

In [7]:
a2 = a.T
a2

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [19]:
for el in a2:
    print(el, type(el))
    print(el.mean())

[1 6] <class 'numpy.ndarray'>
3.5
[2 8] <class 'numpy.ndarray'>
5.0
[ 3 11] <class 'numpy.ndarray'>
7.0
[ 3 10] <class 'numpy.ndarray'>
6.5
[1 7] <class 'numpy.ndarray'>
4.0


In [34]:
# Средние значения для каждого признака
mean_a = np.array([])
for el in a2:
    mean_a = np.append(mean_a, [el.mean()])
mean_a

array([3.5, 5. , 7. , 6.5, 4. ])

### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [36]:
a_centered = a - mean_a
a_centered

array([[-2.5, -3. , -4. , -3.5, -3. ],
       [ 2.5,  3. ,  4. ,  3.5,  3. ]])

_абсолютно непонятна логика задания... может я не понял, что именно надо сделать? Результат такой, как я и ожидал, но логики никакой..._

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [37]:
a_centered_transposed = a_centered.T
a_centered_transposed

array([[-2.5,  2.5],
       [-3. ,  3. ],
       [-4. ,  4. ],
       [-3.5,  3.5],
       [-3. ,  3. ]])

In [38]:
a_centered_sp = np.array([])
for el in a_centered_transposed:
    a_centered_sp = np.append(a_centered_sp, [el[0] * el[1]])
a_centered_sp

array([ -6.25,  -9.  , -16.  , -12.25,  -9.  ])

In [40]:
a_centered_sp_new = a_centered_sp / 1
a_centered_sp_new

array([ -6.25,  -9.  , -16.  , -12.25,  -9.  ])

_опять же, никакой логики в действиях, но сами действия и команды работают ровно так, как я хочу. Если действия надо производить над другими частями матрицы - исправьте меня, переделаю как надо. Формулировка очень запутанная..._

### Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [41]:
check = np.cov(a.T)
check

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

_очень интересно и ничего не понятно, функция выдала ковариационную матрицу формата 5х5, а не 2х2, как написано в задании. Скорее всего в первом задании неправильно дают данные для заданий... И дальше путают столбцы и строки с названиями признака и наблюдения. Не читал еще про ковариацию, не думаю, что она объяснит, почему в заданиях результат разный))_

# Тема “Работа с данными в Pandas”

### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [45]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                       columns= ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [46]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                      'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                      'price': [450, 300, 350, 500, 450, 370, 290]}, 
                     columns= ['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [49]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'right')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [55]:
top5 = authors_price.sort_values(by = 'price').tail(5)
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

_хотя по моему лучше сделать так:_

In [57]:
top5 = authors_price.sort_values(by = 'price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

_очень удобно учить пандас после SQL, знаешьпринципы работы с данными и что точно есть descent sort :)

(в уроках не было свойства ascending для .sort_values() )

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

In [129]:
price_min = authors_price.groupby('author_name').agg({'price': 'min'})
price_min = price_min.reset_index()
price_min

author_name  price
0  Островский    290
1    Тургенев    300
2       Чехов    450

In [133]:
price_max = authors_price.groupby('author_name').agg({'price': 'max'})
price_max = price_max.reset_index()
price_max

author_name  price
0  Островский    370
1    Тургенев    450
2       Чехов    500

In [134]:
price_mean = authors_price.groupby('author_name').agg({'price': 'mean'})
price_mean = price_mean.reset_index()
price_mean

author_name       price
0  Островский  330.000000
1    Тургенев  366.666667
2       Чехов  475.000000

In [147]:
authors_stat = pd.merge(price_min, price_max, on='author_name', how='left')
authors_stat = pd.merge(authors_stat, price_mean, on='author_name', how='left')
authors_stat.columns = ['author_name', 'min_price', 'max_price', 'mean_price']
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

_В уроке не сказано, как работать с .groupby(), абсолютно не раскрыты его свойства и принципы работы, точно так же, как и работа .merge(). Я могу за 3 секунды написать этот запрос на SQL, но тут на это я потратил минут 40..._

### Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [148]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [149]:
?pd.pivot_table

_Уже нет времени еще самостоятельно разбирать полностью новую, миллион первую команду, закончу чуть позже..._